# Generated by Django 5.1.4 on 2025-01-05 05:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название категории')),
                ('slug', models.SlugField(unique=True, verbose_name='Slug')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
            },
        ),
        migrations.CreateModel(
            name='PlantCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название категории растения')),
                ('slug', models.SlugField(unique=True, verbose_name='Slug')),
            ],
            options={
                'verbose_name': 'Категория растений',
                'verbose_name_plural': 'Категории растений',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название товара')),
                ('slug', models.SlugField(unique=True, verbose_name='Slug')),
                ('description', models.CharField(max_length=350, verbose_name='Описание товара')),
                ('plant_name', models.CharField(blank=True, max_length=30, verbose_name='Имя растения')),
                ('plant_height', models.CharField(blank=True, choices=[('Tall', 'От 1 метра и выше'), ('Medium', 'От 50 сантиметров до 1 метра'), ('Small', 'От 15 до 50 сантиметров'), ('Tiny', 'До 15 сантиметров')], max_length=100, verbose_name='Высота растения')),
                ('watering', models.CharField(blank=True, choices=[('Abundantly', 'Влаголюбивое растение'), ('Moderately', 'Умеренно влаголюбивое растение'), ('Rarely', 'Засухоуствойчивое растение')], max_length=200, verbose_name='Отношение растения к поливу')),
                ('conditions', models.CharField(blank=True, choices=[('Light', 'Светолюбивое растение'), ('Moderately', 'Умеренно светолюбивое растение'), ('Dark', 'Тенелюбивое растение')], max_length=100, verbose_name='Отношение растения к свету')),
                ('care', models.CharField(blank=True, choices=[('Easy', 'Легкое в уходе, почти не требующее внимания растение'), ('Medium', 'Простое в уходе, требующее внимания растение'), ('HArd', 'Сложное в уходе растение')], max_length=200, verbose_name='Забота о растении')),
                ('interesting_fact', models.CharField(blank=True, max_length=300, verbose_name='Интересный факт о растении')),
                ('toxic_level', models.CharField(blank=True, choices=[('Safe', 'Абсолютно безопасно'), ('Medium', 'Токсично при употреблении в пищу'), ('Dangerous', 'Токсично')], max_length=200, verbose_name='Токсичность растения')),
                ('price', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Цена товара')),
                ('available', models.BooleanField(default=True, verbose_name='Доступно к продаже')),
                ('main_image', models.ImageField(upload_to='products/', verbose_name='Главное изображение')),
                ('first_detail_image', models.ImageField(blank=True, upload_to='products/', verbose_name='Дополнительное изображение')),
                ('second_detail_image', models.ImageField(blank=True, upload_to='products/', verbose_name='Дополнительное изображение')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='Catalog.category', verbose_name='Категория товара')),
                ('plant_category', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='products', to='Catalog.plantcategory', verbose_name='Категория растения')),
            ],
            options={
                'verbose_name': 'Товар',
                'verbose_name_plural': 'Товары',
            },
        ),
    ]
