# Generated by Django 5.1.4 on 2025-01-05 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Catalog', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='first_detail_image',
        ),
        migrations.RemoveField(
            model_name='product',
            name='second_detail_image',
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(max_length=750, verbose_name='Описание товара'),
        ),
        migrations.AlterField(
            model_name='product',
            name='interesting_fact',
            field=models.TextField(blank=True, max_length=300, verbose_name='Интересный факт о растении'),
        ),
        migrations.AlterField(
            model_name='product',
            name='main_image',
            field=models.ImageField(blank=True, upload_to='products/', verbose_name='Главное изображение'),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=8, verbose_name='Цена товара'),
        ),
    ]
