# Generated by Django 5.1.4 on 2025-01-08 16:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Catalog', '0002_remove_product_first_detail_image_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='care',
        ),
        migrations.RemoveField(
            model_name='product',
            name='conditions',
        ),
        migrations.RemoveField(
            model_name='product',
            name='interesting_fact',
        ),
        migrations.RemoveField(
            model_name='product',
            name='plant_height',
        ),
        migrations.RemoveField(
            model_name='product',
            name='toxic_level',
        ),
        migrations.RemoveField(
            model_name='product',
            name='watering',
        ),
    ]
